### ISSUE TITLE
[Enhancement] Vanish Support

### ISSUE THREAD

**Issue by untuned** [kainlighty/LightStaffList#1]
### Plugin Version

1.1.2

### Select The Core

Purpur

### Description

I would like to see vanish support be added (in my case, SuperVanish or PremiumVanish). We use layered see permissions, so for example an owner could vanish and none of the other staff would know.

**Comment by kainlighty** [comment]
Check version 1.1.2.1. Tried to fulfill your request

**Comment by kainlighty** [comment]
Added
