### ISSUE TITLE
[Bug] No RGB Support

### ISSUE THREAD

**Issue by untuned** [kainlighty/LightStaffList#2]
### Plugin Version

1.1.2

### Select The Core

Purpur

### Description

The screenshot should be self-explanatory.
<img width="227" alt="image" src="https://github.com/kainlighty/LightStaffList/assets/7635652/dd6d3551-f8a0-4b24-b417-8a9d08aa7798">

**Comment by kainlighty** [comment]
#2b6cc4 ADMIN

**Comment by untuned** [comment]
> #2b6cc4 ADMIN

There are a lot more standardized RGB formats, like `&#RRGGBB`.

**Comment by kainlighty** [comment]
Check it out now
