### ISSUE TITLE
Ошибки в новой версии плагина

### ISSUE THREAD

**Issue by PECKMINECRAFT** [kainlighty/LightStaffList#5]
### Plugin Version

1.2.1

### Select The Core

Spigot

### Description

![Screenshot_52](https://github.com/kainlighty/LightStaffList/assets/142804725/32ebf0d5-537c-42a9-9eea-a8fddddf85d0)
![Screenshot_51](https://github.com/kainlighty/LightStaffList/assets/142804725/a4b4fcad-1e5a-4864-aa17-37ba4c305585)
Сверху **ошибки** которые выдаются, как будто локальный сервер не даёт запустить данный плагин. Что уж там, даже сам **LuckPerms** жалуется на запуск плагина по команде **/lightstafflist**

Да, жалуюсь 2 раз, но только здесь. Даже при этом плагин не работает, в чём может быть ошибка?

- **P.S Я не разбираюсь в плагинах, может быть я что-то не понимаю....**

**Comment by PECKMINECRAFT** [comment]
Проблема оказывается в смене ядра

**Comment by kainlighty** [comment]
> Проблема оказывается в смене ядра

Если не сложно, расскажи по подробней

**Comment by PECKMINECRAFT** [comment]
> > Проблема оказывается в смене ядра
> 
> Если не сложно, расскажи по подробней

Просто ядро Spigot не совместим с этим плагином, я поставил ядро Paper (на момент решения) и всё харашо, сейчас другое ядро и всё работает спокойно. Поэтому автор мода, рассмотрите проблемы на стороне Spigot. Извиняюсь что не отвечаю часто, не сижу особо на этой платформе, узнал только через почту про вас.

**Comment by kainlighty** [comment]
> > > Проблема оказывается в смене ядра
> > 
> > 
> > Если не сложно, расскажи по подробней
> 
> Просто ядро Spigot не совместим с этим плагином, я поставил ядро Paper (на момент решения) и всё харашо, сейчас другое ядро и всё работает спокойно. Поэтому автор мода, рассмотрите проблемы на стороне Spigot. Извиняюсь что не отвечаю часто, не сижу особо на этой платформе, узнал только через почту про вас.

Так как я изначально использую paper-api, то предполагаю что в нем нет adventure-api, которое есть в paper. Как видно по логам ругается при отправке сообщение. Spigot видимо не поддерживает это, хотя в зависимостях в проекте есть этот API, правда он не включается в сам jar-файл.

Я просто не особо вижу в нынешних реалиях использовать spigot, поэтому всегда тестирую на paper или его форках (да к тому же чуть больше возможностей с ним).

Отправь версию ядра spigot которое было, попробую adventure-api включить в jar-файл и протестировать. 
Это может помочь исправить ошибку на Spigot ядре для тех, кто его использует (не уверен, но стоит попробовать)

**Comment by PECKMINECRAFT** [comment]
На 

> > > > Проблема оказывается в смене ядра
> > > 
> > > 
> > > Если не сложно, расскажи по подробней
> > 
> > 
> > Просто ядро Spigot не совместим с этим плагином, я поставил ядро Paper (на момент решения) и всё харашо, сейчас другое ядро и всё работает спокойно. Поэтому автор мода, рассмотрите проблемы на стороне Spigot. Извиняюсь что не отвечаю часто, не сижу особо на этой платформе, узнал только через почту про вас.
> 
> Так как я изначально использую paper-api, то предполагаю что в нем нет adventure-api, которое есть в paper. Как видно по логам ругается при отправке сообщение. Spigot видимо не поддерживает это, хотя в зависимостях в проекте есть этот API, правда он не включается в сам jar-файл.
> 
> Я просто не особо вижу в нынешних реалиях использовать spigot, поэтому всегда тестирую на paper или его форках (да к тому же чуть больше возможностей с ним).
> 
> Отправь версию ядра spigot которое было, попробую adventure-api включить в jar-файл и протестировать. Это может помочь исправить ошибку на Spigot ядре для тех, кто его использует (не уверен, но стоит попробовать)

Не отправить файл, 67 мб весит из 25 мб. 
Вот [ссылка ](https://drive.google.com/file/d/1fNhtfs5QfGhkhL2xo0A-dP2iWmOyGdut/view?usp=sharing) на ядро которое у меня стояло

**Comment by kainlighty** [comment]
> На
> 
> > > > > Проблема оказывается в смене ядра
> > > > 
> > > > 
> > > > Если не сложно, расскажи по подробней
> > > 
> > > 
> > > Просто ядро Spigot не совместим с этим плагином, я поставил ядро Paper (на момент решения) и всё харашо, сейчас другое ядро и всё работает спокойно. Поэтому автор мода, рассмотрите проблемы на стороне Spigot. Извиняюсь что не отвечаю часто, не сижу особо на этой платформе, узнал только через почту про вас.
> > 
> > 
> > Так как я изначально использую paper-api, то предполагаю что в нем нет adventure-api, которое есть в paper. Как видно по логам ругается при отправке сообщение. Spigot видимо не поддерживает это, хотя в зависимостях в проекте есть этот API, правда он не включается в сам jar-файл.
> > Я просто не особо вижу в нынешних реалиях использовать spigot, поэтому всегда тестирую на paper или его форках (да к тому же чуть больше возможностей с ним).
> > Отправь версию ядра spigot которое было, попробую adventure-api включить в jar-файл и протестировать. Это может помочь исправить ошибку на Spigot ядре для тех, кто его использует (не уверен, но стоит попробовать)
> 
> Не отправить файл, 67 мб весит из 25 мб. Вот [ссылка ](https://drive.google.com/file/d/1fNhtfs5QfGhkhL2xo0A-dP2iWmOyGdut/view?usp=sharing) на ядро которое у меня стояло

Версию понял. Протестирую. Спасибо :)
Если пофикшу, укажу в обновлении и если так нужен spigot, то сможешь использовать этот плагин с ним.

**Comment by PECKMINECRAFT** [comment]
> > На
> > > > > > Проблема оказывается в смене ядра
> > > > > 
> > > > > 
> > > > > Если не сложно, расскажи по подробней
> > > > 
> > > > 
> > > > Просто ядро Spigot не совместим с этим плагином, я поставил ядро Paper (на момент решения) и всё харашо, сейчас другое ядро и всё работает спокойно. Поэтому автор мода, рассмотрите проблемы на стороне Spigot. Извиняюсь что не отвечаю часто, не сижу особо на этой платформе, узнал только через почту про вас.
> > > 
> > > 
> > > Так как я изначально использую paper-api, то предполагаю что в нем нет adventure-api, которое есть в paper. Как видно по логам ругается при отправке сообщение. Spigot видимо не поддерживает это, хотя в зависимостях в проекте есть этот API, правда он не включается в сам jar-файл.
> > > Я просто не особо вижу в нынешних реалиях использовать spigot, поэтому всегда тестирую на paper или его форках (да к тому же чуть больше возможностей с ним).
> > > Отправь версию ядра spigot которое было, попробую adventure-api включить в jar-файл и протестировать. Это может помочь исправить ошибку на Spigot ядре для тех, кто его использует (не уверен, но стоит попробовать)
> > 
> > 
> > Не отправить файл, 67 мб весит из 25 мб. Вот [ссылка ](https://drive.google.com/file/d/1fNhtfs5QfGhkhL2xo0A-dP2iWmOyGdut/view?usp=sharing) на ядро которое у меня стояло
> 
> Версию понял. Протестирую. Спасибо :) Если пофикшу, укажу в обновлении и если так нужен spigot, то сможешь использовать этот плагин с ним.

Да пожалуйста, рад помочь людям, которые разбираются в создании плагинов и тд. Интересный опыт, но spigot как ядро я так понимаю плохое, для этого Paper - самый топ для этого плагина. Сейчас использую Purpur, и плагин с ним совместим и слава богу <3 :)

**Comment by kainlighty** [comment]
Можешь скачать lightcheck в моем профиле, там есть эта библиотека. Если он будет работать корректно, то значит проблема в этом. Просто запусти и введи /check, можешь даже в консоли.
